//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_307_Project
{


    public partial class Main
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox TextBoxWord;

        protected global::System.Web.UI.WebControls.TextBox TextBoxYear;

        protected global::System.Web.UI.WebControls.DropDownList ddlDomain;

        protected global::System.Web.UI.WebControls.DropDownList ddlLang;

        protected global::System.Web.UI.WebControls.DropDownList ddlUni;

        protected global::System.Web.UI.WebControls.DropDownList ddlInst;

        protected global::System.Web.UI.WebControls.DropDownList ddlType;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.Button btnClean;

        protected global::System.Web.UI.WebControls.Label lblClean;

        protected global::System.Web.UI.WebControls.GridView gvThesis;

        protected global::System.Web.UI.WebControls.BoundField author;
        
        protected global::System.Web.UI.WebControls.BoundField lang;

        protected global::System.Web.UI.WebControls.BoundField uni;

        protected global::System.Web.UI.WebControls.BoundField inst;

        protected global::System.Web.UI.WebControls.BoundField super;

        protected global::System.Web.UI.WebControls.BoundField cosuper;

        protected global::System.Web.UI.WebControls.BoundField no;

        protected global::System.Web.UI.WebControls.BoundField title;

        protected global::System.Web.UI.WebControls.BoundField year;

        protected global::System.Web.UI.WebControls.BoundField abs;

        protected global::System.Web.UI.WebControls.BoundField type;

        protected global::System.Web.UI.WebControls.BoundField pages;

        protected global::System.Web.UI.WebControls.BoundField date;


    }
}
