//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SE_307_Project
{
    public partial class UpdatePage
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtUni;

        protected global::System.Web.UI.WebControls.TextBox txtLocation;

        protected global::System.Web.UI.WebControls.TextBox txtInst;

        protected global::System.Web.UI.WebControls.TextBox txtPersonName;

        protected global::System.Web.UI.WebControls.TextBox txtPersonSurname;

        protected global::System.Web.UI.WebControls.TextBox txtSubject;

        protected global::System.Web.UI.WebControls.Button btnUpdateUni;

        protected global::System.Web.UI.WebControls.Button btnUpdateInst;

        protected global::System.Web.UI.WebControls.Button btnUpdatePerson;

        protected global::System.Web.UI.WebControls.Button btnUpdateSubject;

        protected global::System.Web.UI.WebControls.Button btnRefresh;

        protected global::System.Web.UI.WebControls.Label lblUpdateSuccesUni;

        protected global::System.Web.UI.WebControls.Label lblUpdateSuccesInst;

        protected global::System.Web.UI.WebControls.Label lblUpdateSuccesPerson;

        protected global::System.Web.UI.WebControls.Label lblUpdateSuccesSubject;

        protected global::System.Web.UI.WebControls.DropDownList ddlUni;

        protected global::System.Web.UI.WebControls.DropDownList ddlUniInst;

        protected global::System.Web.UI.WebControls.DropDownList ddlInst;

        protected global::System.Web.UI.WebControls.DropDownList ddlPerson;

        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;


    }
}
