//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SE_307_Project
{
    public partial class AddPage
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Button btnAddPerson;

        protected global::System.Web.UI.WebControls.Button btnAddUni;

        protected global::System.Web.UI.WebControls.Button btnAddEnst;

        protected global::System.Web.UI.WebControls.Button btnAddLang;

        protected global::System.Web.UI.WebControls.Button btnSubject;

        protected global::System.Web.UI.WebControls.Button btnRefresh;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtSurname;

        protected global::System.Web.UI.WebControls.TextBox txtUniName;

        protected global::System.Web.UI.WebControls.TextBox txtLocation;

        protected global::System.Web.UI.WebControls.TextBox txtEns;

        protected global::System.Web.UI.WebControls.TextBox txtLang;

        protected global::System.Web.UI.WebControls.TextBox txtSubject;

        protected global::System.Web.UI.WebControls.DropDownList ddlPerson;

        protected global::System.Web.UI.WebControls.DropDownList ddlUni;

        protected global::System.Web.UI.WebControls.Label lblsuccesPerson;

        protected global::System.Web.UI.WebControls.Label lblfailPerson;

        protected global::System.Web.UI.WebControls.Label lblSuccesSubject;

        protected global::System.Web.UI.WebControls.Label lblErrorSubject;

        protected global::System.Web.UI.WebControls.Label lblsuccesUni;

        protected global::System.Web.UI.WebControls.Label lblfailUni;

        protected global::System.Web.UI.WebControls.Label lblsuccesEnst;

        protected global::System.Web.UI.WebControls.Label lblfailEnst;

        protected global::System.Web.UI.WebControls.Label lblsuccesLang;

        protected global::System.Web.UI.WebControls.Label lblfailLang;
    }
}
